### ISSUE TITLE
Skipping first frame in eval?

### ISSUE THREAD

**Issue by mseitzer** [google-research/slot-attention-video#10]
Hi, 

in the SAVi paper it says
> For both FG-ARI and mIoU, we skip the first frame during evaluation as we provide conditional information (e.g., bounding boxes) for it in most cases.

I am wondering where this happens in the code? I was not able to find it after quite some searching, but I may misinterpret the JAX code somehow.

Thanks!

**Comment by tkipf** [comment]
Thanks for your question! Your observation is correct: we indeed do not drop the first frame during metric calculation in this code release. We will update the README to clarify this discrepancy with the paper.
