### ISSUE TITLE
It seems that num_heads for SlotAttention is 1?

### ISSUE THREAD

**Issue by wcarvalho** [google-research/slot-attention-video#13]
I'm a little confused about the code. I'm following [this config](https://github.com/google-research/slot-attention-video/blob/main/savi/configs/movi/savi_conditional_small.py). It seems that Slot Attention only has 1 head in all configs? If so, does that mean there is only 1 slot? If not, could you help me understand how the number of slots determined in the code?

**Comment by ruili3** [comment]
The default slot number is shown [here](https://github.com/google-research/slot-attention-video/blob/ba8f15ee19472c6f9425c9647daf87910f17b605/savi/configs/movi/savi_conditional_small.py#L71). The Slot Attention you mentioned refers to the number of attention modules used in SAVi

**Comment by wcarvalho** [comment]
Thank you, this answer my question!
